### ISSUE TITLE
Unable to connect to SMRA

### ISSUE THREAD

**Issue by alicebyers5** [Health-SocialCare-Scotland/phiproject#3]
When trying to connect to SMRA from within the project, I get the following error:
`Error: nanodbc/nanodbc.cpp:950: 08004: [unixODBC][Oracle][ODBC][Ora]ORA-12154: TNS:could not resolve the connect identifier specified`

I've tested in a fresh untouched phiproject (to check it's nothing I've done) and I get the same error. I've also tested the same code in a new session (not in a project) and it successfully connects. 

This is following the workflow of creating the project via R Studio Desktop (as server doesn't support GitHub package install) and then opening and working on the project using R Studio Server.

**Comment by alan-y** [comment]
Can you try connecting to SMRA using a new ordinary R project (rather than PHI project) please? Maybe its an issue with using projects...

**Comment by alicebyers5** [comment]
Tried in an ordinary project and can connect fine..

**Comment by annahprice** [comment]
Did you create that project on the desktop and then open on the server to connect to SMRA, in the same way as before?

**Comment by alicebyers5** [comment]
Sorry to say but yes! 🙁

**Comment by alan-y** [comment]
Ok one more thing to try, can you create a phiproject, then delete the .renviron and .rprofile files from the folder (possibly delete .gitignore as well)

**Comment by alicebyers5** [comment]
Yep, works if I delete these in desktop before then opening project on server.

**Comment by alan-y** [comment]
Excellent thanks, it'll be something to do with how R looks for your odbc credentials or something. I'll close the issue and follow this up off Github.
